### ISSUE TITLE
Consider using renv

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#1]
@netique Pro jistotu dodávám linky, co jsem klukům posílal emailem než ses připojil:

https://environments.rstudio.com/
https://github.com/rstudio/renv
https://rstudio.github.io/renv/

**Comment by jaromir-mazak** [comment]
@netique Honzo, díval ses na to?

**Comment by netique** [comment]
Zkoušel jsem to orientačně použít a ta práce je taková složitější... Když začnu nový projekt, musím znovu instalovat všechny balíky. Možná nejlepší je normálně pracovat a `renv` pak nastavit, když se aktualizují balíky nebo se projekt archivuje či posílá. Jakmile člověk udá všechny `library(...)`, tak si to samo zjistí, co používáš, a uloží.

**Comment by petrbouchal** [comment]
Vidíš, to mě nenapadlo, že je tam ta bariéra na začátku instalovat balíky (ale: pokud se jedna verze už jednou v nějakém projektu použije, je to pak minimálně rychlejší a vše se jen prolinkuje z cache, takže nikde neleží duplikáty balíků a do gitu se committuje navíc jen ten lockfile.)

Určitě bych doporučoval i při průběžné práci - z mé zkušenosti to eliminuje ty chyby, kdy dva lidi, co na něčem spolupracují, mají trochu jinou verzi něčeho. Moje zkušenost je, že když si člověk na těch pár kroků navíc zvykne, tak je člověku dost odlehčí jeden typ starostí.

Ale souhlas, že je lepší něco kódu napsat a pak až dát `renv::init()`.

Nebudu tedy to šablony projektu vepisovat žádnou automatiku, jen přidám noticku do dokumentace.

**Comment by jaromir-mazak** [comment]
OK, díky oběma za vyřešení, souhlasím.
