### ISSUE TITLE
Schola ggplot2 theme

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#2]

**Comment by petrbouchal** [comment]
Otázky pro @jaromir-mazak @alesvomacka @netique 👍 

- je bílé pozadí OK, nebo chceme moct celou plochu grafu ve wordu vizuálně odlišit pozadím, aby bylo poznat, kde graf začíná a končí?
- je barva pozadí OK? Chtěl jsem něco, co by nevypadalo jako technická default šedá...
- jsou parametry theme_schola() pochopitelné a smysluplné?
- dává vám smysl moje úvaha o popiscích os?
- není ten výsledek příliš osekaný (za mě ne, ale taky jsem někdy příliš minimalista)
- chtěli byste nějaké jiné zkratky/defaulty, abyste dokola nenastavovali věci někde v hloubi `theme(this.thing.I.always.forget = element_crap(this.weird.param = unit("what!!"))`?

Barevné schéma samotných datových prvků (barevné škály a default barvy) budeme řešit zvlášť.

**Comment by jaromir-mazak** [comment]
Bavíme se o tom spolu na callu:

- je bílé pozadí OK, nebo chceme moct celou plochu grafu ve wordu vizuálně odlišit pozadím, aby bylo poznat, kde graf začíná a končí?
BÍLE POZADÍ JE OK.

- je barva pozadí OK? Chtěl jsem něco, co by nevypadalo jako technická default šedá...
BARVA POZADÍ JE OK, MOC SE NÁM LÍBÍ.

- jsou parametry theme_schola() pochopitelné a smysluplné?
ANO (PŘÍPADNĚ DÁME VĚDĚT, KDYBYCHOM TO ZAČALI VNÍMAT V PRAXI JINAK)

- dává vám smysl moje úvaha o popiscích os?
ANO,  v případě, že popisek chceme, používáme přednostně (labs(title="...",
        x ="...", y = "..."), nikoliv xlab a ylab

- není ten výsledek příliš osekaný (za mě ne, ale taky jsem někdy příliš minimalista)
JE SUPER.

- chtěli byste nějaké jiné zkratky/defaulty, abyste dokola nenastavovali věci někde v hloubi theme(this.thing.I.always.forget = element_crap(this.weird.param = unit("what!!"))?
ZATÍM DOBRÉ, PŘÍPADNĚ SE OZVEME.

- máte nějaké názory k písmu?
BEREME ROBOTO A ROBOTO CONDENSED

**Comment by petrbouchal** [comment]
Ahoj pánové @jaromir-mazak @netique @alesvomacka ,

Mohli byste prosím příležitostně pustit na svých strojích v čerstvě nastartovaném RStudio tento kód a dát vědět, co to dělá (očekávání v komentářích)? Pokud uvidíte chyby, hoďte je prosím do komentáře. Pokud graf vypadá jinak než bychom čekali, hoďte prosím do komentáře screen shot nebo export.

Ideálně kdybyste to zkusili i v konzoli i v Rmd chunku.

Díky!!

```
remove.packages(c("reschola", "redoc", "diffobj")) # abychom mohli otestovat instalaci

options(repos = c(getOption("repos"), "scholaempirica" = "scholaempirica.github.io/drat"))
install.packages("reschola")

library(reschola) # načte se bez chyb?
library(redoc) # jen pro kontrolu - načte se bez chyb?

import_fonts() # proběhne? Plus nainstalujte pak písma na svůj počítač
set_reschola_ggplot_fonts() # OK, bez chyb?

library(ggplot2)

data <- mpg[mpg$manufacturer=='audi',]
data$class[data$class=='midsize'] <- "šťň"
data$class[data$class=='compact'] <- "ůúěéá"
p <- ggplot(data, aes(hwy, cty)) + 
  geom_text(aes(label = class)) +
  ggtitle("Hodně načeřená", "a vyňuňaná auta pro taťku")
p 
# text uvnitř grafy by měl být v Roboto Condensed a s diakritikou
p + theme_schola()
# i text v nadpisech by měl být v Roboto [Condensed] a s diakritikou
p + theme_schola(title_family = font_r_light)
# možná hodí chybu nebo text v nadpise nebude v Roboto? Nebo je jen tenčí?
p + theme_schola(title_family = font_rc_light)
# možná hodí chybu nebo text v nadpise nebude v Roboto? Nebo je jen tenčí?
```

**Comment by jaromir-mazak** [comment]
Mně ta instalace balíku ani tímto způsobem nefunguje:

![image](https://user-images.githubusercontent.com/61726523/76998536-8d2e9b80-6955-11ea-96a6-ac73f633aae2.png)

**Comment by jaromir-mazak** [comment]
A nefunguje ani ten způsob, co jsi mi dříve posílal v emailu:
![image](https://user-images.githubusercontent.com/61726523/76998830-ff9f7b80-6955-11ea-8ee2-d63c3b34fd8b.png)

**Comment by petrbouchal** [comment]
Hmm tak to zkus nainstalovat zatím přes remotes/devtools, já mezitím
prozkoumám co je s tím drat-em

**Comment by petrbouchal** [comment]
Případně pak prosím zkus s opraveným kódem nahoře. Dík!

**Comment by jaromir-mazak** [comment]
Po příkazu "reschola::import_fonts()" se objeví "
***
You will likely need to install these fonts on your system as well.

You can find them in [C:/Users/mazak/OneDrive/Dokumenty/R/win-library/3.6/reschola/fonts/roboto]
You will likely need to install these fonts on your system as well
***

Přišlo by mi prima, kdyby tam byla i instrukce:
"On Windows 7 or newer, this can be done by right-clicking on the font file and selecting Install."

(Jinak jsem to musel Googlovat.)

**Comment by jaromir-mazak** [comment]
remotes/devtools funguje, balík mám, teď si lámu hlavu, jak posoudit, jestli je to roboto, jsem na tyhle věci trochu slepý :-) 
ale font se mění, asi nejjednodušší bude sem hodit obrázky těch grafů postupně za sebou

**Comment by jaromir-mazak** [comment]
![image](https://user-images.githubusercontent.com/61726523/77006018-09c77700-6962-11ea-88c6-a4b145bf8495.png)

![image](https://user-images.githubusercontent.com/61726523/77006042-12b84880-6962-11ea-9c84-2cc180e8393e.png)

![image](https://user-images.githubusercontent.com/61726523/77006056-1946c000-6962-11ea-856d-15d070afe6a1.png)

![image](https://user-images.githubusercontent.com/61726523/77006075-206dce00-6962-11ea-803e-5b2bc13debb8.png)


A tedy ten poslední jako jediný hází warning:
Warning messages:
1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
2: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
3: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database

**Comment by petrbouchal** [comment]
Super, díky. To vypadá robře, i když s tímhle rozlišením bych za ty rozdíly ruku do ohně nedal. Vypadají ta písmenka uvnitř grafu stejně jako v těch nadpisech v druhém grafu? Případně pošli nějaký high-res export asi mailem...

To třetí je jinde zdokumentovaná chyba, takže Roboto Condensed Light asi z balíku vytáhnu, respektive nebude mít tu zkratku.

**Comment by petrbouchal** [comment]
Ad ta instalace z .../drat, kdyby to pořád nešlo s tím upraveným kódem, hledal bych řešení někde tady https://support.rstudio.com/hc/en-us/articles/206827897-Secure-Package-Downloads-for-R

**Comment by jaromir-mazak** [comment]
Podívám se na to, grafy ve vyšším rozlišení pošlu.
Ještě jsem našel toto, kdyby to bylo užitečné třeba při tom výběru barev nebo dolaďování toho našeho theme (nebo prostě pro budoucí využití):
https://github.com/hrbrmstr/hrbrthemes

**Comment by petrbouchal** [comment]
Jojo, hrbrthemes jsou super, odsud i znovyvyužíváme nějaké kompontenty, abychom nepsali znovu to samé...

**Comment by jaromir-mazak** [comment]
Ty grafy, co jsem poslal na mail vznikly takto

```{r }
p <- ggplot(data, aes(hwy, cty)) +
  geom_text(aes(label = class)) +
  ggtitle("Hodně načeřená", "a vyňůňaná aúta pro taťku")
p

ggsave(filename = "graf1.png", dpi = 300, type = "cairo",
       width = 4, height = 3, units = "in")

# text uvnitř grafy by měl být v Roboto Condensed a s diakritikou
p + theme_schola()
ggsave(filename = "graf2.png", dpi = 300, type = "cairo",
       width = 4, height = 3, units = "in")

# i text v nadpisech by měl být v Roboto [Condensed] a s diakritikou
p + theme_schola(title_family = font_r_light)
ggsave(filename = "graf3.png", dpi = 300, type = "cairo",
       width = 4, height = 3, units = "in")

# možná hodí chybu nebo text v nadpise nebude v Roboto? Nebo je jen tenčí?
p + theme_schola(title_family = font_rc_light)
ggsave(filename = "graf4.png", dpi = 300, type = "cairo",
       width = 4, height = 3, units = "in")
# možná hodí chybu nebo text v nadpise nebude v Roboto? Nebo je jen tenčí?

```

**Comment by petrbouchal** [comment]
Aha, tak soudě podle obrázků v mailu je to jak jsem se bál z náhledů - tam, kde má být Roboto Condensed, je jen defaultní serif (asi Arial). Zkusil bys kdyžtak restartovat R, načíst rescholu, pro jistotu pustit `extrafont::loadfonts()` a pak zkusil znovu vygenerovat ty grafy jak to máš o koment výš? Případně zkontrolovat, jestli máš ta Roboto Condensed opravdu v systému?

A vypadá ten PNG soubor z `ggsave()` stejně jako to co vidíš v Plot panelu v RStudiu?

**Comment by petrbouchal** [comment]
Taky dost divně vypadá graf 3 - tam to asi substituuje nějaký divný light font...

**Comment by jaromir-mazak** [comment]
Tohle mi to hodí v RStudio:
![image](https://user-images.githubusercontent.com/61726523/77062435-286a5400-69dc-11ea-9d31-58d6fe8aab0b.png)


V systému jsem ty fonty našel ve skryté složce, kde ale nejsou žádné jiné:
![image](https://user-images.githubusercontent.com/61726523/77062504-46d04f80-69dc-11ea-9b0f-e39ee4f8c209.png)

V R pak warningy hází pořád jen ten 4. graf.

> p + theme_schola(title_family = font_rc_light)
Warning messages:
1: In grid.Call(C_stringMetric, as.graphicsAnnot(x$label)) :
  font family not found in Windows font database
2: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
3: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
4: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
> ggsave(filename = "graf4.png", dpi = 300, type = "cairo", width = 4, height = 3, units = "in")
Warning messages:
1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
2: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
3: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
4: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
5: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database
6: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database

Nové grafy podle mě vypadají pořád stejně, pošlu emailem. 

Jinak font asi není to nejdůležitější, kdyby se to na tom mělo zaseknout a byla jednodušší alternativa, tak můžeme vzít něco jiného.

**Comment by petrbouchal** [comment]
Díky. Přijde mi divné, že ve složce ten font (Roboto Condensed) nevidíš a přitom R hlásí, že ho vidí dvakrát. Myslím že je zakopaný pes někde v tom, kam se ti to na počítači instaluje. Příležitostně ještě koukni do písem v nastavení nebo jak se to jmenuje, viz https://www.lifewire.com/install-fonts-in-windows-7-4160580.

Uvidíme co kluci.

**Comment by jaromir-mazak** [comment]
Od chvíle, co se snažím dělat něco jiného než surfovat na internetu, otevřít MS Word nebo hrát hledání min docela lituju, že používám Windows...

**Comment by jaromir-mazak** [comment]
Hele, tak se omlouvám, to asi nejde za Windows, ale za mnou, já jsem si nevšiml, že to Roboto Condensed se instaluje v jiném balíku, ne v reschola. Tak v emailu nové grafy - teď už to vypadá skutečně na Roboto.

**Comment by petrbouchal** [comment]
Super. Trochu jsem v nové verzi upravil, jak se zobrazují instrukce k instalaci fontů, tak by se tohle přehlétnutí mělo stát míň snadno.
