### ISSUE TITLE
Consider standard validation

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#20]
- https://docs.ropensci.org/assertr/
- https://cran.r-project.org/web/packages/validate/vignettes/introduction.html

**Comment by jaromir-mazak** [comment]
Dohodli jsme se, že se na to podívá Honza v rámci zpracování dat SDQ, kde se to může dobře vyzkoušet.

**Comment by jaromir-mazak** [comment]
@netique Honzo, jak to vypadá, jsou už nějaké výsledky, které by šlo inegrovat do našeho workflow?

**Comment by netique** [comment]
Zítra se pokusím jít s tím na GH. Zkoušel jsem jen `assertr`, ten mi přišel fajn. Zprvu se mi nepozdávalo, že to vyhazuje závěry jako chybu, kvůli které třeba nejde "zkompilovat" _RMarkdown_, ale je to pojistka proti načtení špatných dat, nebo i průběžně při další práci. A samozřejmě to jde i změnit na výstup formou _tibble_ apod.

**Comment by netique** [comment]
Stale, closing for now...
