### ISSUE TITLE
Allow checking that input CSVs are UTF-8

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#25]

**Comment by petrbouchal** [comment]
Note to self: this could actually be done through some heavy-duty use of `readr::guess_encoding()`

**Comment by jaromir-mazak** [comment]
@petrbouchal jestli správně tuším, jak funguje guess_encoding, tak by to fungovalo, jen pokud by tam bylo dost stringového textu, ne? 
tohle asi nepovažuji za tak důležité issue, myslím, že si to zvládneme pohlídat a uložit do utf-8 než do nahrajeme do složky na GDrive

**Comment by petrbouchal** [comment]
Jo, myslím že to je přiměřené řešení...
