### ISSUE TITLE
Figure out optimal combination of settings for image output in Word

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#37]

**Comment by petrbouchal** [comment]
Assumptions:

- A4 paper
- margins 2.5 cm on left and right
- DPI of 300 for nice printing
- standard text in plot should be same optical size as paragraph text in document
- plot title size should be +1/+2 pts
- plot dimensions: usually full-
[test.docx](https://github.com/scholaempirica/reschola/files/4400028/test.docx)
width, height approx. in golden ratio (.61 times width)
- document text is Arial (very similar optical size to Roboto)

Results:

- set default width of 6.29 in (16 cm), aspect ratio of .61 (done in output format in package - this is the default for the template which can be overridden at file or chunk level)
- base size in ggplot2 of 11 (the default in `schola_*` formats), title size is by default +2 pts
- dpi of 300 for nice printing
- can set smaller width by setting both out.width to X/2.54 and fig.width to "Xcm", where X is the desired width in cm. Then font size will be right.

All committed in code; Word output
[test.docx](https://github.com/scholaempirica/reschola/files/4400030/test.docx)
 attached for inspection.

Niggling question for @jaromir-mazak 

When rendering MS Word from Rmarkdown, there is probably no way to put the figure caption above the figure (seems to be hard-coded in Pandoc). That means we cannot use it as the title. But we do need the caption *if* we want to be able to cross-reference (i.e. referring to figures in text such that the figure number updates automatically). One option would be to make the figure caption Word style quite small. Is that OK? (Being able to cross-reference also requires that you set the name and fig.cap option for the chunk.)

**Comment by jaromir-mazak** [comment]
@netique @alesvomacka 

díky, @petrbouchal , mně se to moc líbí, co myslíte vy, kluci?

tu "Niggling question" moc nechápu, konkrétně toto: "One option would be to make the figure caption Word style quite small. Is that OK?"  To je něco, co je vidět v tom test.doxc? Přesně nevím, jak to myslíš.

**Comment by petrbouchal** [comment]
Jo to tam je, případně můžeme ještě zmenšit. Jen je pak blbý, že odkazuješ
na "obrázek 1", přičemž nadpis v obrázku žádné číslo neobsahuje a popisek
Obrázek 1 je dole v malém...

**Comment by jaromir-mazak** [comment]
aha, v tom testovém dokumentu ale u obrázku nevidím ani ten malý popisek dole. vidím tam jen "Viz obrázek 1 - this reference is automatically numbered." ale už ne, na co to referencuje. proto jsem se ptal. ale myslím, že už tomu rozumím, prostě by se pod obrázek přidal text "Obrázek 1", který by byl ve zvoleném wordovém formátu, pravděpodobně jako malý, třeba velikostí 10. 

Alternativy:
- žádné cross-reference, ale číslování natvrdo u hotového dokumentu
- nepoužívat Title v ggplot, ale až ve Wordu (s tou nevýhodou, že pak nadpis automaticky necestuje s obrázkem třeba do prezentace, na web nebo do FB postu.

Probereme to a dáme vědět. Díky!

**Comment by petrbouchal** [comment]
Díky @jaromir-mazak tak jsme právě otestovali special case, že když se udělá hack se dvěma obrázky naráz, caption se nezobrazí. Přikládám opravené.

Ta druhá varianta má právě ten problém, že bys musel manuálně přesouvat captions nad graf... Vlastně mi ta varianta ukázaná v příkladu nepřijde úplně blbá.

[test.docx](https://github.com/scholaempirica/reschola/files/4408093/test.docx)

**Comment by jaromir-mazak** [comment]
Super, tak jsem rád, že mé zmatení bylo oprávněné :-)
Mně se to takhle také dost líbí. Vlastně to má i výhody: číslo není součástí nadpisu, takže když obrázek cestuje třeba do prezentace, na web atp. tak není potřeba řešit. Já bych  šel touto cestou. Díky za řešení!

**Comment by jaromir-mazak** [comment]
@petrbouchal ještě jsem si uvědomi, že jsme tu nedořešili: je to teď opravené i tak, že to hodí caption pro ty dv obrázky? v testu je to jen pod standardním obrázkem. chtěl jsem to zkusit, ale nejde mi teď vytvořit nový projekt, kde předpokládám, že je to součástí nějaké šablony? nebo jak bych to vlatně mohl zkusit?

**Comment by petrbouchal** [comment]
Ty dva obrázky jsou trochu hack, se kterým na rozhraní knitr-pandoc vzniká problém s caption a to vyřešit neumíme. Na dvojobrázky stejně doporučuju balík `patchwork`, umí to skvěle vše zarovnat a sladit legendy.

```
library(ggplot2)
library(patchwork)

p1 <- ggplot(mpg) + geom_point(aes(cty, hwy, fill = manufacturer), shape = 21, key_glyph = draw_key_rect)
p2 <- ggplot(mpg) + geom_bar(aes(hwy, fill = manufacturer), key_glyph = draw_key_rect) + coord_flip()

p1 + p2 + plot_layout(guides = "collect")
```

Zkusit šablony můžeš v jakémkoli projektu, jen si pusť `reschola::draft_word()`.
