### ISSUE TITLE
Add guidance on locale

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#50]
@jaromir-mazak Mohl bys mi prosím napsat - pokud si pamatuješ - k jakému tomu sys.setlocale() jsme dospěli? Bylo tam kdesi Czechia si pamatuju, ale pak už nevím... A taky nevím, jestli jsme tam nějak dostali to UTF-8, nebo tam bylo nějaké podivné kódování? Dík!

**Comment by jaromir-mazak** [comment]
když teď otevřu R, tak se mi vždy napíše: 

R version 3.6.3 (2020-02-29) -- "Holding the Windsock"
...
Type 'q()' to quit R.

[1] "LC_COLLATE=Czech_Czechia.1250;LC_CTYPE=Czech_Czechia.1250;LC_MONETARY=Czech_Czechia.1250;LC_NUMERIC=C;LC_TIME=Czech_Czechia.1250"

Předpokládám, že to je to, co potřebuješ :-)

**Comment by petrbouchal** [comment]
a písmenka teď všude dobrý, jo? 
Připíšu to do dokumentace.

**Comment by jaromir-mazak** [comment]
Nevšiml jsem si problémů, zkoušel jsem ty tvé grafy z dokumentace k Reschola, kde jsi testoval různá písmenka, a také mapy v balíku sf a vše dobré.
