### ISSUE TITLE
Feedback & finalise: setup guide

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#51]
Pánové: guide k instalaci a nastavení všeho je na https://scholaempirica.github.io/reschola/articles/setup.html. Pokusil jsem se tam vtělit všechno, co jsme procházeli na začátku, plus nějaký background. Trochu jsem balancoval, kde dát extrakt z jiných zdrojů, kde to přepsat sám a kde jen odkázat, tak snad to nějak funguje.

Dejte prosím vědět, pokud vám tam něco chybí/nesedí.

Vím, že chybí část k locales #50 a k renv #1 (tam potřebuju input od vás).

Díky.

**Comment by alesvomacka** [comment]
Za mě dobrý. Tady je kdyžtak návod na instalci R/Rstudia/tidyverse pro naše studenty, pokud byste se někdo chtěli inspirovat a přidat do guidu. Ale za mě asi není potřeba
[R_instalace.pdf](https://github.com/scholaempirica/reschola/files/4371761/R_instalace.pdf)

**Comment by jaromir-mazak** [comment]
#50 tam jsem teď komentoval
#1 na tom pracuje Honza

jinak mi ten popis setup také přijde srozumitelný

**Comment by petrbouchal** [comment]
Ještě doplnit tyhle věci, pak hotovo:

- RStudio Cloud
- Set CRAN mirror
- Explainer of R setup dotfiles
