### ISSUE TITLE
Feedback & finalise: tips collection

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#53]
Tips and tricks collection na https://scholaempirica.github.io/reschola/articles/tips.html - asi méně prioritní, ale i tady budu rád za input.

**Comment by alesvomacka** [comment]
Za mě boží. Obecně bych byl pro nějakou složku/stránku, kam bychom házeli tipy a triky na analýzu (tipu: můžete použít list() a tím vytvořit vnořený dataframe v rámci mutate). Tahle poznámka je hlavně proto, abych nezapomněl, že to chci probrat na dalším setkání.

**Comment by petrbouchal** [comment]
Nejčistší by mi přišlo psát to rovnou do té vignette - jakmile uděláš push, aktualizuje se to na webu. Nebo na další tipy a triky můžeme udělat novou vignette.

Anebo wiki, ale pak se to začne dost drobit...
