### ISSUE TITLE
Feedback & finalise: package updating guide

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#54]
Tohle bych byl rád, aby bylo pro vás dobře čitelné, takže pokud něco nedává smysl, pište.
https://scholaempirica.github.io/reschola/articles/meta.html

**Comment by alesvomacka** [comment]
Za mě dobrý. Mimochodem, jaká je šance tenhle balíček protlačit na CRAN? Pokud je cílem šířit evaluace a analýzu dál do neziskového sektoru (což bych rád), tak by to asi pomohlo.

**Comment by petrbouchal** [comment]
Teď budeme zaseklí na té dependency na `redoc`, který není na CRAN - obecně CRAN nebere balíky, které závisí na něčem mimo CRAN, nemluvě o té obezličce, co jsem tam udělal s tou opravou `redoc`...

**Comment by jaromir-mazak** [comment]
za mě dokumentace také dobrá, smysl dává.
