### ISSUE TITLE
Provide alternative project setup workflow outside project template

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#60]

**Comment by petrbouchal** [comment]
@netique @alesvomacka pokud vám projektová šablona funguje bez chyb, toto bych zavřel a případně obnovil a dořešil, pokud se objeví problémy.

**Comment by jaromir-mazak** [comment]
@petrbouchal 
já už jsem s tím v minulosti dva projekty založil a fungovalo to dobře, ale dnes mi to hodilo chybu:
Error in link_copy(links, path(new_path[[i]], path_rel(links, path[[i]])),  : 
  all(is_link(path)) is not TRUE

**Comment by petrbouchal** [comment]
Uf to je blbý, sorry. Něco mě napadá, pojďme zkusit poladit na callu, kdyžtak to ale pak dodělám.

Kdyžtak mi sem hoď screenshot, co se v tom adresáři nového projektu vytvořilo, a verzi reschola?

Co @netique & @alesvomacka: funguje vám to?

**Comment by jaromir-mazak** [comment]
vytvořilo to tohle:
[image: image.png]

rescholu pošlu, mám zrovna calll :(

pá 3. 4. 2020 v 8:10 odesílatel Petr Bouchal <notifications@github.com>
napsal:

**Comment by jaromir-mazak** [comment]
tak ještě ta verze
packageVersion("reschola")
[1] ‘0.2.9’


pá 3. 4. 2020 v 10:21 odesílatel Jaromír Mazák <mazak.jaromir@gmail.com>
napsal:

**Comment by jaromir-mazak** [comment]
vidím, že se sem z emailu nepropsal ten screenshot

![image](https://user-images.githubusercontent.com/61726523/78340236-08b75c00-7596-11ea-90c7-f71e53a3ed5d.png)
