### ISSUE TITLE
Function to add logo to charts

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#69]
https://github.com/TomFranklin/r-ggplot2-adding-logo
https://stackoverflow.com/questions/29370734/adding-a-logo-to-multi-plot-output-in-r-or-ggplot2
https://gist.github.com/hrbrmstr/6e353b8da97a1a1098ec053781b7bdac#file-footer-png
https://stackoverflow.com/questions/26644728/add-image-png-file-to-header-of-pdf-file-created-with-r/26851776#26851776
https://michaeltoth.me/you-need-to-start-branding-your-graphs-heres-how-with-ggplot.html

**Comment by netique** [comment]
I think this is solved with a custom template within a project root. See `schola_word2` for details.
