### ISSUE TITLE
Allow custom figure dimensions

### ISSUE THREAD

**Issue by netique** [scholaempirica/reschola#71]
Figures are rendered with fixed dimensions which are good looking and useful 95% of the time.  However, **sometimes there is a need for manual resize** – it seems impossible to achieve this with common chunk directives, e.g. `fig.width` or `out.width`.

**Comment by jaromir-mazak** [comment]
this is important, we now lack control over size of some charts, especially problem when faceting. is it a bug, or is there a good working solution?

**Comment by petrbouchal** [comment]
A piece of documentation explaining this is on the way.

**Comment by petrbouchal** [comment]
Yup - not a bug but maintaining the right output requires a trick when changing sizes - now documented at https://scholaempirica.github.io/reschola/articles/charts.html#sizing-images-1. (via c948478b0174b7e19d52211afc8623d707f37aa8 which also closes #70 )

@netique @jaromir-mazak can you please check if that makes sense, works, and serves your need?

**Comment by netique** [comment]
OK, it works just fine. I've later realized that aspect ratio is fixed to golden ratio. The default is required most of the time anyway, so keep it as is.
