### ISSUE TITLE
Fix and document font issues with PDF

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#72]
"invalid font"
- see https://github.com/hrbrmstr/hrbrthemes/issues/18 and 
- the solution should be to implement our own font import with own files - specifically with files in hrbrthemes but without RC Light
- or do above and also run code suggested as fix in https://github.com/hrbrmstr/hrbrthemes/issues/18 as part of `import_fonts()`.

"dot substituted..."
- see https://stackoverflow.com/questions/13251665/rhtml-warning-conversion-failure-on-var-in-mbcstosbcs-dot-substituted-f/13299607#13299607 - probably only relevent on Macs?

Also need note on `embed_fonts()`.

Alternatively, it seems `cairo_pdf` does not throw the latter error, at least on a Mac.

**Comment by petrbouchal** [comment]
@jaromir-mazak @alesvomacka can you let me know if in the end you do need the PDF template/way to output PDF docs? If so, I may have figured out an optimal way to handle reschola-themed fonts in charts for PDF, but it would require some testing on your machines. (I would leave the LaTex styling to you though...)

**Comment by alesvomacka** [comment]
I would definitely appreciate it.

**Comment by petrbouchal** [comment]
@alesvomacka did any of what I suggested via email re fonts work?

**Comment by alesvomacka** [comment]
> 
> 
> @alesvomacka did any of what I suggested via email re fonts work?

@petrbouchal word graph changes work (the size of graphs needs to be changed through aspect ratio, not directly).

As for PDF, no combination of solutions work for me.

**Comment by petrbouchal** [comment]
OK - can you please try to 'Knit' (via RStudio button) the Rmd file in the attached ZIP and post back the resulting PDF after running `extrafont::embed_fonts("reschola_pdf_fonts_testpad.pdf")`?
[reschola_pdf_fonts_testpad.Rmd.zip](https://github.com/scholaempirica/reschola/files/4586776/reschola_pdf_fonts_testpad.Rmd.zip)

**Comment by netique** [comment]
There is `schola_pdf` format now in v0.2.13.9000. Please check & close.
