### ISSUE TITLE
Word template

### ISSUE THREAD

**Issue by jaromir-mazak** [scholaempirica/reschola#75]
It would be great to have the Word template generated within project (not in the pckg) to be able to easily change it for project needs. This can be part of a subsequent commission we would like to discuss later. In addition, there is now no straightforward way to make page break in Markdown which would work for Word documents (neither \newpage nor \pagebreak seem to work. It would be great to integrate it, sth like this: https://datascienceplus.com/r-markdown-how-to-insert-page-breaks-in-a-ms-word-document/#:~:text=RStudio%20offers%20the%20opportunity%20to,final%20MS%20Word%20output%20file.

**Comment by petrbouchal** [comment]
Just briefly re page breaks: `\newpage` works on my machine, as it should per https://cran.r-project.org/web/packages/rmarkdown/vignettes/lua-filters.html. Perhaps st about versions of {rmarkdown} and pandoc?

**Comment by petrbouchal** [comment]
Also make sure there are blank lines before and after?

**Comment by jaromir-mazak** [comment]
oh, it actually only did not work for the first time in the document i tried to use it and worked just fine for all the other instances (i did not try other instances yesterday. i only made it work in the first instance using the command twice:

![image](https://user-images.githubusercontent.com/61726523/83857684-a1e02b80-a71b-11ea-9c20-e884fe233c07.png)

i suspect it may be redoc related issue, but no idea.

**Comment by petrbouchal** [comment]
Aaaah yes - I can replicate the error now: when the \newpage is the first thing with `output: reschola::schola_redoc`, it does nothing. I suspect that's a different between `rmarkdown::word_document`, which is under the hood of `schola_redoc`, and `bookdown::word_document2` which is under the hood of `schola_word`. If you can identify this you might want to file an issue with {rmarkdown} but more likely this happens at the interface of {rmarkdown} and {redoc}...

**Comment by netique** [comment]
`schola_word()` now allows for custom template and utilizes the default, packed in `reschola` if none provided. However, using `Word` template is discouraged and probably will be soft-deprecated in the future.
