### ISSUE TITLE
Generate proper Czech quotes in RMarkdown output

### ISSUE THREAD

**Issue by petrbouchal** [scholaempirica/reschola#76]
Can be done using https://github.com/odkr/pandoc-quotes.lua/blob/master/pandoc-quotes.lua but we will need to work that into the package & templates so that (a) no extra setup is required in the Rmd doc & (b) no per-machine setup is required.

**Comment by jaromir-mazak** [comment]
Nice, just consider that some reports are in English, so it should be possible to opt in both ways of quoting easily.

**Comment by petrbouchal** [comment]
Indeed - I've just tested it elsewhere and there is a YAML option for switching the language.

**Comment by petrbouchal** [comment]
FYI - was trying to implement this myself and this seems to be the right way to do it inside a custom output format: https://rmarkdown.rstudio.com/docs/articles/lua-filters.html#using-filters-with-output-format

Presumably you'd want to store the Lua filter file in the package and point to it using `reschola_file()`. Plus perhaps update your Rmd templates to provide params and defaults in YAML for the Lua script to customise language etc.
