### ISSUE TITLE
Make wrapper for GDrive API (to be able to upload files)

### ISSUE THREAD

**Issue by netique** [scholaempirica/reschola#85]
Using GDrive as a live storage is extremely impracticall and leads to reproducibility issues like https://github.com/scholaempirica/eduzmena_wave_1/issues/2.

**Comment by petrbouchal** [comment]
You might also want to explore the {pins} package or rely more on {targets} via S3?

**Comment by netique** [comment]
{pins} doesn't support gdrive yet, solved with gd_upload().
